export enum ECitiesActionTypes {
  CITIES_REQUEST = 'CITIES_REQUEST',
  CITIES_RECEIVE = 'CITIES_RECEIVE',
  CITIES_FAILURE = 'CITIES_FAILURE',
  CITIES_CLEAR = 'CITIES_CLEAR',

  CHANGE_CURRENT_CITY = 'CHANGE_CURRENT_CITY'
}