export enum EProductsActionTypes {
  PRODUCTS_REQUEST = 'PRODUCTS_REQUEST',
  PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE',
  PRODUCTS_FILTER = 'PRODUCTS_FILTER',
  PRODUCTS_FAILURE = 'PRODUCTS_FAILURE',
  PRODUCTS_CLEAR = 'PRODUCTS_CLEAR'
}