export {ECategoriesActionTypes as categoriesTypes} from './types'
export {default as categoriesActions} from './actions'
export {default as reducer} from './reducers'
export {default as categoriesSelector} from './selectors'
export {default as categoriesOperations} from './thunks'