export enum ECategoriesActionTypes {
  CATEGORIES_REQUEST = 'CATEGORIES_REQUEST',
  CATEGORIES_RECEIVE = 'CATEGORIES_RECEIVE',
  CATEGORIES_FAILURE = 'CATEGORIES_FAILURE',
  CATEGORIES_CLEAR = 'CATEGORIES_CLEAR',

  CHANGE_SELECTED_CATEGORIES = 'CHANGE_SELECTED_CATEGORIES'
}