export enum EVisibilityFilterActionTypes {
  CITY_FILTER_CHANGE = 'CITY_FILTER_CHANGE',
  CATEGORY_FILTER_CHANGE = 'CATEGORY_FILTER_CHANGE',
  PRICE_FILTER_CHANGE = 'PRICE_FILTER_CHANGE',
  FILTER_CLEAR = 'FILTER_CLEAR',
}